/*
 * Copyright (c) 2023 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.exporter.v0.jooq.pg.tables.records;

import org.ehrbase.migration.exporter.v0.jooq.pg.tables.AdminDeleteTenantFull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AdminDeleteTenantFullRecord extends TableRecordImpl<AdminDeleteTenantFullRecord>
        implements Record1<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.admin_delete_tenant_full.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.admin_delete_tenant_full.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Boolean> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Boolean> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Boolean> field1() {
        return AdminDeleteTenantFull.ADMIN_DELETE_TENANT_FULL.DELETED;
    }

    @Override
    public Boolean component1() {
        return getDeleted();
    }

    @Override
    public Boolean value1() {
        return getDeleted();
    }

    @Override
    public AdminDeleteTenantFullRecord value1(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public AdminDeleteTenantFullRecord values(Boolean value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminDeleteTenantFullRecord
     */
    public AdminDeleteTenantFullRecord() {
        super(AdminDeleteTenantFull.ADMIN_DELETE_TENANT_FULL);
    }

    /**
     * Create a detached, initialised AdminDeleteTenantFullRecord
     */
    public AdminDeleteTenantFullRecord(Boolean deleted) {
        super(AdminDeleteTenantFull.ADMIN_DELETE_TENANT_FULL);

        setDeleted(deleted);
        resetChangedOnNotNull();
    }
}
