/*
 * Copyright (c) 2023 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.exporter.v0.jooq.pg.tables.records;

import java.time.OffsetDateTime;
import java.util.UUID;
import org.ehrbase.migration.exporter.v0.jooq.pg.tables.EhrFolder;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record16;
import org.jooq.Record3;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EhrFolderRecord extends UpdatableRecordImpl<EhrFolderRecord>
        implements Record16<
                UUID,
                UUID,
                Integer,
                Integer,
                UUID,
                UUID,
                String,
                String[],
                String,
                String,
                Integer,
                UUID[],
                JSONB,
                Integer,
                OffsetDateTime,
                Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.ehr_folder.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>ehr.ehr_folder.ehr_id</code>.
     */
    public void setEhrId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.ehr_id</code>.
     */
    public UUID getEhrId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>ehr.ehr_folder.ehr_folders_idx</code>.
     */
    public void setEhrFoldersIdx(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.ehr_folders_idx</code>.
     */
    public Integer getEhrFoldersIdx() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ehr.ehr_folder.row_num</code>.
     */
    public void setRowNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.row_num</code>.
     */
    public Integer getRowNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ehr.ehr_folder.contribution_id</code>.
     */
    public void setContributionId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.contribution_id</code>.
     */
    public UUID getContributionId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>ehr.ehr_folder.audit_id</code>.
     */
    public void setAuditId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.audit_id</code>.
     */
    public UUID getAuditId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>ehr.ehr_folder.archetype_node_id</code>.
     */
    public void setArchetypeNodeId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.archetype_node_id</code>.
     */
    public String getArchetypeNodeId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ehr.ehr_folder.path</code>.
     */
    public void setPath(String[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.path</code>.
     */
    public String[] getPath() {
        return (String[]) get(7);
    }

    /**
     * Setter for <code>ehr.ehr_folder.hierarchy_idx</code>.
     */
    public void setHierarchyIdx(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.hierarchy_idx</code>.
     */
    public String getHierarchyIdx() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ehr.ehr_folder.hierarchy_idx_cap</code>.
     */
    public void setHierarchyIdxCap(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.hierarchy_idx_cap</code>.
     */
    public String getHierarchyIdxCap() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ehr.ehr_folder.hierarchy_idx_len</code>.
     */
    public void setHierarchyIdxLen(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.hierarchy_idx_len</code>.
     */
    public Integer getHierarchyIdxLen() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>ehr.ehr_folder.items</code>.
     */
    public void setItems(UUID[] value) {
        set(11, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.items</code>.
     */
    public UUID[] getItems() {
        return (UUID[]) get(11);
    }

    /**
     * Setter for <code>ehr.ehr_folder.fields</code>.
     */
    public void setFields(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.fields</code>.
     */
    public JSONB getFields() {
        return (JSONB) get(12);
    }

    /**
     * Setter for <code>ehr.ehr_folder.sys_version</code>.
     */
    public void setSysVersion(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.sys_version</code>.
     */
    public Integer getSysVersion() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>ehr.ehr_folder.sys_period_lower</code>.
     */
    public void setSysPeriodLower(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.sys_period_lower</code>.
     */
    public OffsetDateTime getSysPeriodLower() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>ehr.ehr_folder.sys_tenant</code>.
     */
    public void setSysTenant(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder.sys_tenant</code>.
     */
    public Short getSysTenant() {
        return (Short) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, UUID, Short> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<
                    UUID,
                    UUID,
                    Integer,
                    Integer,
                    UUID,
                    UUID,
                    String,
                    String[],
                    String,
                    String,
                    Integer,
                    UUID[],
                    JSONB,
                    Integer,
                    OffsetDateTime,
                    Short>
            fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<
                    UUID,
                    UUID,
                    Integer,
                    Integer,
                    UUID,
                    UUID,
                    String,
                    String[],
                    String,
                    String,
                    Integer,
                    UUID[],
                    JSONB,
                    Integer,
                    OffsetDateTime,
                    Short>
            valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return EhrFolder.EHR_FOLDER.ID;
    }

    @Override
    public Field<UUID> field2() {
        return EhrFolder.EHR_FOLDER.EHR_ID;
    }

    @Override
    public Field<Integer> field3() {
        return EhrFolder.EHR_FOLDER.EHR_FOLDERS_IDX;
    }

    @Override
    public Field<Integer> field4() {
        return EhrFolder.EHR_FOLDER.ROW_NUM;
    }

    @Override
    public Field<UUID> field5() {
        return EhrFolder.EHR_FOLDER.CONTRIBUTION_ID;
    }

    @Override
    public Field<UUID> field6() {
        return EhrFolder.EHR_FOLDER.AUDIT_ID;
    }

    @Override
    public Field<String> field7() {
        return EhrFolder.EHR_FOLDER.ARCHETYPE_NODE_ID;
    }

    @Override
    public Field<String[]> field8() {
        return EhrFolder.EHR_FOLDER.PATH;
    }

    @Override
    public Field<String> field9() {
        return EhrFolder.EHR_FOLDER.HIERARCHY_IDX;
    }

    @Override
    public Field<String> field10() {
        return EhrFolder.EHR_FOLDER.HIERARCHY_IDX_CAP;
    }

    @Override
    public Field<Integer> field11() {
        return EhrFolder.EHR_FOLDER.HIERARCHY_IDX_LEN;
    }

    @Override
    public Field<UUID[]> field12() {
        return EhrFolder.EHR_FOLDER.ITEMS;
    }

    @Override
    public Field<JSONB> field13() {
        return EhrFolder.EHR_FOLDER.FIELDS;
    }

    @Override
    public Field<Integer> field14() {
        return EhrFolder.EHR_FOLDER.SYS_VERSION;
    }

    @Override
    public Field<OffsetDateTime> field15() {
        return EhrFolder.EHR_FOLDER.SYS_PERIOD_LOWER;
    }

    @Override
    public Field<Short> field16() {
        return EhrFolder.EHR_FOLDER.SYS_TENANT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getEhrId();
    }

    @Override
    public Integer component3() {
        return getEhrFoldersIdx();
    }

    @Override
    public Integer component4() {
        return getRowNum();
    }

    @Override
    public UUID component5() {
        return getContributionId();
    }

    @Override
    public UUID component6() {
        return getAuditId();
    }

    @Override
    public String component7() {
        return getArchetypeNodeId();
    }

    @Override
    public String[] component8() {
        return getPath();
    }

    @Override
    public String component9() {
        return getHierarchyIdx();
    }

    @Override
    public String component10() {
        return getHierarchyIdxCap();
    }

    @Override
    public Integer component11() {
        return getHierarchyIdxLen();
    }

    @Override
    public UUID[] component12() {
        return getItems();
    }

    @Override
    public JSONB component13() {
        return getFields();
    }

    @Override
    public Integer component14() {
        return getSysVersion();
    }

    @Override
    public OffsetDateTime component15() {
        return getSysPeriodLower();
    }

    @Override
    public Short component16() {
        return getSysTenant();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getEhrId();
    }

    @Override
    public Integer value3() {
        return getEhrFoldersIdx();
    }

    @Override
    public Integer value4() {
        return getRowNum();
    }

    @Override
    public UUID value5() {
        return getContributionId();
    }

    @Override
    public UUID value6() {
        return getAuditId();
    }

    @Override
    public String value7() {
        return getArchetypeNodeId();
    }

    @Override
    public String[] value8() {
        return getPath();
    }

    @Override
    public String value9() {
        return getHierarchyIdx();
    }

    @Override
    public String value10() {
        return getHierarchyIdxCap();
    }

    @Override
    public Integer value11() {
        return getHierarchyIdxLen();
    }

    @Override
    public UUID[] value12() {
        return getItems();
    }

    @Override
    public JSONB value13() {
        return getFields();
    }

    @Override
    public Integer value14() {
        return getSysVersion();
    }

    @Override
    public OffsetDateTime value15() {
        return getSysPeriodLower();
    }

    @Override
    public Short value16() {
        return getSysTenant();
    }

    @Override
    public EhrFolderRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EhrFolderRecord value2(UUID value) {
        setEhrId(value);
        return this;
    }

    @Override
    public EhrFolderRecord value3(Integer value) {
        setEhrFoldersIdx(value);
        return this;
    }

    @Override
    public EhrFolderRecord value4(Integer value) {
        setRowNum(value);
        return this;
    }

    @Override
    public EhrFolderRecord value5(UUID value) {
        setContributionId(value);
        return this;
    }

    @Override
    public EhrFolderRecord value6(UUID value) {
        setAuditId(value);
        return this;
    }

    @Override
    public EhrFolderRecord value7(String value) {
        setArchetypeNodeId(value);
        return this;
    }

    @Override
    public EhrFolderRecord value8(String[] value) {
        setPath(value);
        return this;
    }

    @Override
    public EhrFolderRecord value9(String value) {
        setHierarchyIdx(value);
        return this;
    }

    @Override
    public EhrFolderRecord value10(String value) {
        setHierarchyIdxCap(value);
        return this;
    }

    @Override
    public EhrFolderRecord value11(Integer value) {
        setHierarchyIdxLen(value);
        return this;
    }

    @Override
    public EhrFolderRecord value12(UUID[] value) {
        setItems(value);
        return this;
    }

    @Override
    public EhrFolderRecord value13(JSONB value) {
        setFields(value);
        return this;
    }

    @Override
    public EhrFolderRecord value14(Integer value) {
        setSysVersion(value);
        return this;
    }

    @Override
    public EhrFolderRecord value15(OffsetDateTime value) {
        setSysPeriodLower(value);
        return this;
    }

    @Override
    public EhrFolderRecord value16(Short value) {
        setSysTenant(value);
        return this;
    }

    @Override
    public EhrFolderRecord values(
            UUID value1,
            UUID value2,
            Integer value3,
            Integer value4,
            UUID value5,
            UUID value6,
            String value7,
            String[] value8,
            String value9,
            String value10,
            Integer value11,
            UUID[] value12,
            JSONB value13,
            Integer value14,
            OffsetDateTime value15,
            Short value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EhrFolderRecord
     */
    public EhrFolderRecord() {
        super(EhrFolder.EHR_FOLDER);
    }

    /**
     * Create a detached, initialised EhrFolderRecord
     */
    public EhrFolderRecord(
            UUID id,
            UUID ehrId,
            Integer ehrFoldersIdx,
            Integer rowNum,
            UUID contributionId,
            UUID auditId,
            String archetypeNodeId,
            String[] path,
            String hierarchyIdx,
            String hierarchyIdxCap,
            Integer hierarchyIdxLen,
            UUID[] items,
            JSONB fields,
            Integer sysVersion,
            OffsetDateTime sysPeriodLower,
            Short sysTenant) {
        super(EhrFolder.EHR_FOLDER);

        setId(id);
        setEhrId(ehrId);
        setEhrFoldersIdx(ehrFoldersIdx);
        setRowNum(rowNum);
        setContributionId(contributionId);
        setAuditId(auditId);
        setArchetypeNodeId(archetypeNodeId);
        setPath(path);
        setHierarchyIdx(hierarchyIdx);
        setHierarchyIdxCap(hierarchyIdxCap);
        setHierarchyIdxLen(hierarchyIdxLen);
        setItems(items);
        setFields(fields);
        setSysVersion(sysVersion);
        setSysPeriodLower(sysPeriodLower);
        setSysTenant(sysTenant);
        resetChangedOnNotNull();
    }
}
