/*
 * Copyright (c) 2023 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.exporter.v0.jooq.pg.tables.records;

import org.ehrbase.migration.exporter.v0.jooq.pg.tables.Heading;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HeadingRecord extends UpdatableRecordImpl<HeadingRecord>
        implements Record4<String, String, String, Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.heading.code</code>.
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.heading.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ehr.heading.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ehr.heading.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ehr.heading.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ehr.heading.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ehr.heading.sys_tenant</code>.
     */
    public void setSysTenant(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>ehr.heading.sys_tenant</code>.
     */
    public Short getSysTenant() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Heading.HEADING.CODE;
    }

    @Override
    public Field<String> field2() {
        return Heading.HEADING.NAME;
    }

    @Override
    public Field<String> field3() {
        return Heading.HEADING.DESCRIPTION;
    }

    @Override
    public Field<Short> field4() {
        return Heading.HEADING.SYS_TENANT;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Short component4() {
        return getSysTenant();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Short value4() {
        return getSysTenant();
    }

    @Override
    public HeadingRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public HeadingRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public HeadingRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public HeadingRecord value4(Short value) {
        setSysTenant(value);
        return this;
    }

    @Override
    public HeadingRecord values(String value1, String value2, String value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HeadingRecord
     */
    public HeadingRecord() {
        super(Heading.HEADING);
    }

    /**
     * Create a detached, initialised HeadingRecord
     */
    public HeadingRecord(String code, String name, String description, Short sysTenant) {
        super(Heading.HEADING);

        setCode(code);
        setName(name);
        setDescription(description);
        setSysTenant(sysTenant);
        resetChangedOnNotNull();
    }
}
