/*
 * Copyright (c) 2023 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.exporter.v0.jooq.pg.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import org.ehrbase.migration.exporter.v0.jooq.pg.Ehr;
import org.ehrbase.migration.exporter.v0.jooq.pg.Keys;
import org.ehrbase.migration.exporter.v0.jooq.pg.tables.records.HeadingRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Heading extends TableImpl<HeadingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.heading</code>
     */
    public static final Heading HEADING = new Heading();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HeadingRecord> getRecordType() {
        return HeadingRecord.class;
    }

    /**
     * The column <code>ehr.heading.code</code>.
     */
    public final TableField<HeadingRecord, String> CODE =
            createField(DSL.name("code"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>ehr.heading.name</code>.
     */
    public final TableField<HeadingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.heading.description</code>.
     */
    public final TableField<HeadingRecord, String> DESCRIPTION =
            createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.heading.sys_tenant</code>.
     */
    public final TableField<HeadingRecord, Short> SYS_TENANT = createField(
            DSL.name("sys_tenant"),
            SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)),
            this,
            "");

    private Heading(Name alias, Table<HeadingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Heading(Name alias, Table<HeadingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.heading</code> table reference
     */
    public Heading(String alias) {
        this(DSL.name(alias), HEADING);
    }

    /**
     * Create an aliased <code>ehr.heading</code> table reference
     */
    public Heading(Name alias) {
        this(alias, HEADING);
    }

    /**
     * Create a <code>ehr.heading</code> table reference
     */
    public Heading() {
        this(DSL.name("heading"), null);
    }

    public <O extends Record> Heading(Table<O> child, ForeignKey<O, HeadingRecord> key) {
        super(child, key, HEADING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ehr.EHR;
    }

    @Override
    public UniqueKey<HeadingRecord> getPrimaryKey() {
        return Keys.HEADING_PKEY;
    }

    @Override
    public List<ForeignKey<HeadingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HEADING__HEADING_SYS_TENANT_FKEY);
    }

    private transient Tenant _tenant;

    /**
     * Get the implicit join path to the <code>ehr.tenant</code> table.
     */
    public Tenant tenant() {
        if (_tenant == null) _tenant = new Tenant(this, Keys.HEADING__HEADING_SYS_TENANT_FKEY);

        return _tenant;
    }

    @Override
    public Heading as(String alias) {
        return new Heading(DSL.name(alias), this);
    }

    @Override
    public Heading as(Name alias) {
        return new Heading(alias, this);
    }

    @Override
    public Heading as(Table<?> alias) {
        return new Heading(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Heading rename(String name) {
        return new Heading(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Heading rename(Name name) {
        return new Heading(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Heading rename(Table<?> name) {
        return new Heading(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(
            Function4<? super String, ? super String, ? super String, ? super Short, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
            Class<U> toType,
            Function4<? super String, ? super String, ? super String, ? super Short, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
