/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import org.ehrbase.migration.importer.v4.jooq.pg.Ehr;
import org.ehrbase.migration.importer.v4.jooq.pg.Keys;
import org.ehrbase.migration.importer.v4.jooq.pg.enums.ContributionChangeType;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.records.AuditDetailsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class AuditDetails extends TableImpl<AuditDetailsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.audit_details</code>
     */
    public static final AuditDetails AUDIT_DETAILS = new AuditDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditDetailsRecord> getRecordType() {
        return AuditDetailsRecord.class;
    }

    /**
     * The column <code>ehr.audit_details.id</code>.
     */
    public final TableField<AuditDetailsRecord, UUID> ID =
            createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.audit_details.change_type</code>.
     */
    public final TableField<AuditDetailsRecord, ContributionChangeType> CHANGE_TYPE = createField(
            DSL.name("change_type"),
            SQLDataType.VARCHAR
                    .nullable(false)
                    .asEnumDataType(org.ehrbase.migration.importer.v4.jooq.pg.enums.ContributionChangeType.class),
            this,
            "");

    /**
     * The column <code>ehr.audit_details.description</code>.
     */
    public final TableField<AuditDetailsRecord, String> DESCRIPTION =
            createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.audit_details.time_committed</code>.
     */
    public final TableField<AuditDetailsRecord, OffsetDateTime> TIME_COMMITTED = createField(
            DSL.name("time_committed"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>ehr.audit_details.committer</code>.
     */
    public final TableField<AuditDetailsRecord, JSONB> COMMITTER =
            createField(DSL.name("committer"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>ehr.audit_details.user_id</code>.
     */
    public final TableField<AuditDetailsRecord, UUID> USER_ID =
            createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.audit_details.target_type</code>.
     */
    public final TableField<AuditDetailsRecord, String> TARGET_TYPE =
            createField(DSL.name("target_type"), SQLDataType.VARCHAR.nullable(false), this, "");

    private AuditDetails(Name alias, Table<AuditDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuditDetails(Name alias, Table<AuditDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.audit_details</code> table reference
     */
    public AuditDetails(String alias) {
        this(DSL.name(alias), AUDIT_DETAILS);
    }

    /**
     * Create an aliased <code>ehr.audit_details</code> table reference
     */
    public AuditDetails(Name alias) {
        this(alias, AUDIT_DETAILS);
    }

    /**
     * Create a <code>ehr.audit_details</code> table reference
     */
    public AuditDetails() {
        this(DSL.name("audit_details"), null);
    }

    public <O extends Record> AuditDetails(Table<O> child, ForeignKey<O, AuditDetailsRecord> key) {
        super(child, key, AUDIT_DETAILS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ehr.EHR;
    }

    @Override
    public UniqueKey<AuditDetailsRecord> getPrimaryKey() {
        return Keys.AUDIT_DETAILS_PKEY;
    }

    @Override
    public List<ForeignKey<AuditDetailsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUDIT_DETAILS__AUDIT_DETAILS_USER_ID_FKEY);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>ehr.users</code> table.
     */
    public Users users() {
        if (_users == null) _users = new Users(this, Keys.AUDIT_DETAILS__AUDIT_DETAILS_USER_ID_FKEY);

        return _users;
    }

    @Override
    public AuditDetails as(String alias) {
        return new AuditDetails(DSL.name(alias), this);
    }

    @Override
    public AuditDetails as(Name alias) {
        return new AuditDetails(alias, this);
    }

    @Override
    public AuditDetails as(Table<?> alias) {
        return new AuditDetails(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDetails rename(String name) {
        return new AuditDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDetails rename(Name name) {
        return new AuditDetails(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDetails rename(Table<?> name) {
        return new AuditDetails(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, ContributionChangeType, String, OffsetDateTime, JSONB, UUID, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(
            Function7<
                            ? super UUID,
                            ? super ContributionChangeType,
                            ? super String,
                            ? super OffsetDateTime,
                            ? super JSONB,
                            ? super UUID,
                            ? super String,
                            ? extends U>
                    from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
            Class<U> toType,
            Function7<
                            ? super UUID,
                            ? super ContributionChangeType,
                            ? super String,
                            ? super OffsetDateTime,
                            ? super JSONB,
                            ? super UUID,
                            ? super String,
                            ? extends U>
                    from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
