/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import org.ehrbase.migration.importer.v4.jooq.pg.Indexes;
import org.ehrbase.migration.importer.v4.jooq.pg.Keys;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.records.CompVersionRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CompVersion extends TableImpl<CompVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.comp_version</code>
     */
    public static final CompVersion COMP_VERSION = new CompVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompVersionRecord> getRecordType() {
        return CompVersionRecord.class;
    }

    /**
     * The column <code>ehr.comp_version.vo_id</code>.
     */
    public final TableField<CompVersionRecord, UUID> VO_ID =
            createField(DSL.name("vo_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.ehr_id</code>.
     */
    public final TableField<CompVersionRecord, UUID> EHR_ID =
            createField(DSL.name("ehr_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.contribution_id</code>.
     */
    public final TableField<CompVersionRecord, UUID> CONTRIBUTION_ID =
            createField(DSL.name("contribution_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.audit_id</code>.
     */
    public final TableField<CompVersionRecord, UUID> AUDIT_ID =
            createField(DSL.name("audit_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.template_id</code>.
     */
    public final TableField<CompVersionRecord, UUID> TEMPLATE_ID =
            createField(DSL.name("template_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.sys_version</code>.
     */
    public final TableField<CompVersionRecord, Integer> SYS_VERSION =
            createField(DSL.name("sys_version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.sys_period_lower</code>.
     */
    public final TableField<CompVersionRecord, OffsetDateTime> SYS_PERIOD_LOWER = createField(
            DSL.name("sys_period_lower"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>ehr.comp_version.root_concept</code>.
     */
    public final TableField<CompVersionRecord, String> ROOT_CONCEPT =
            createField(DSL.name("root_concept"), SQLDataType.CLOB.nullable(false), this, "");

    private CompVersion(Name alias, Table<CompVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private CompVersion(Name alias, Table<CompVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.comp_version</code> table reference
     */
    public CompVersion(String alias) {
        this(DSL.name(alias), COMP_VERSION);
    }

    /**
     * Create an aliased <code>ehr.comp_version</code> table reference
     */
    public CompVersion(Name alias) {
        this(alias, COMP_VERSION);
    }

    /**
     * Create a <code>ehr.comp_version</code> table reference
     */
    public CompVersion() {
        this(DSL.name("comp_version"), null);
    }

    public <O extends Record> CompVersion(Table<O> child, ForeignKey<O, CompVersionRecord> key) {
        super(child, key, COMP_VERSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : org.ehrbase.migration.importer.v4.jooq.pg.Ehr.EHR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.COMP_VERSION_SYS_PERIOD_LOWER_IDX);
    }

    @Override
    public UniqueKey<CompVersionRecord> getPrimaryKey() {
        return Keys.COMP_VERSION_PKEY;
    }

    @Override
    public List<ForeignKey<CompVersionRecord, ?>> getReferences() {
        return Arrays.asList(
                Keys.COMP_VERSION__COMP_VERSION_EHR_ID_FKEY,
                Keys.COMP_VERSION__COMP_VERSION_CONTRIBUTION_ID_FKEY,
                Keys.COMP_VERSION__COMP_VERSION_AUDIT_ID_FKEY,
                Keys.COMP_VERSION__COMP_VERSION_TEMPLATE_ID_FKEY);
    }

    private transient org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr _ehr;
    private transient Contribution _contribution;
    private transient AuditDetails _auditDetails;
    private transient TemplateStore _templateStore;

    /**
     * Get the implicit join path to the <code>ehr.ehr</code> table.
     */
    public org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr ehr() {
        if (_ehr == null)
            _ehr = new org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr(
                    this, Keys.COMP_VERSION__COMP_VERSION_EHR_ID_FKEY);

        return _ehr;
    }

    /**
     * Get the implicit join path to the <code>ehr.contribution</code> table.
     */
    public Contribution contribution() {
        if (_contribution == null)
            _contribution = new Contribution(this, Keys.COMP_VERSION__COMP_VERSION_CONTRIBUTION_ID_FKEY);

        return _contribution;
    }

    /**
     * Get the implicit join path to the <code>ehr.audit_details</code> table.
     */
    public AuditDetails auditDetails() {
        if (_auditDetails == null)
            _auditDetails = new AuditDetails(this, Keys.COMP_VERSION__COMP_VERSION_AUDIT_ID_FKEY);

        return _auditDetails;
    }

    /**
     * Get the implicit join path to the <code>ehr.template_store</code> table.
     */
    public TemplateStore templateStore() {
        if (_templateStore == null)
            _templateStore = new TemplateStore(this, Keys.COMP_VERSION__COMP_VERSION_TEMPLATE_ID_FKEY);

        return _templateStore;
    }

    @Override
    public CompVersion as(String alias) {
        return new CompVersion(DSL.name(alias), this);
    }

    @Override
    public CompVersion as(Name alias) {
        return new CompVersion(alias, this);
    }

    @Override
    public CompVersion as(Table<?> alias) {
        return new CompVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompVersion rename(String name) {
        return new CompVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompVersion rename(Name name) {
        return new CompVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompVersion rename(Table<?> name) {
        return new CompVersion(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, UUID, UUID, UUID, Integer, OffsetDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(
            Function8<
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super Integer,
                            ? super OffsetDateTime,
                            ? super String,
                            ? extends U>
                    from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
            Class<U> toType,
            Function8<
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super Integer,
                            ? super OffsetDateTime,
                            ? super String,
                            ? extends U>
                    from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
