/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import org.ehrbase.migration.importer.v4.jooq.pg.Keys;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.records.EhrStatusDataRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EhrStatusData extends TableImpl<EhrStatusDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.ehr_status_data</code>
     */
    public static final EhrStatusData EHR_STATUS_DATA = new EhrStatusData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EhrStatusDataRecord> getRecordType() {
        return EhrStatusDataRecord.class;
    }

    /**
     * The column <code>ehr.ehr_status_data.vo_id</code>.
     */
    public final TableField<EhrStatusDataRecord, UUID> VO_ID =
            createField(DSL.name("vo_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.num</code>.
     */
    public final TableField<EhrStatusDataRecord, Integer> NUM =
            createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.ehr_id</code>.
     */
    public final TableField<EhrStatusDataRecord, UUID> EHR_ID =
            createField(DSL.name("ehr_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.citem_num</code>.
     */
    public final TableField<EhrStatusDataRecord, Integer> CITEM_NUM =
            createField(DSL.name("citem_num"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ehr.ehr_status_data.rm_entity</code>.
     */
    public final TableField<EhrStatusDataRecord, String> RM_ENTITY =
            createField(DSL.name("rm_entity"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_concept</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_CONCEPT =
            createField(DSL.name("entity_concept"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_name</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_NAME =
            createField(DSL.name("entity_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_attribute</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_ATTRIBUTE =
            createField(DSL.name("entity_attribute"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_path</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_PATH =
            createField(DSL.name("entity_path"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_path_cap</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_PATH_CAP =
            createField(DSL.name("entity_path_cap"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_idx</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_IDX =
            createField(DSL.name("entity_idx"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_idx_cap</code>.
     */
    public final TableField<EhrStatusDataRecord, String> ENTITY_IDX_CAP =
            createField(DSL.name("entity_idx_cap"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.entity_idx_len</code>.
     */
    public final TableField<EhrStatusDataRecord, Integer> ENTITY_IDX_LEN =
            createField(DSL.name("entity_idx_len"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data.data</code>.
     */
    public final TableField<EhrStatusDataRecord, JSONB> DATA =
            createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "");

    private EhrStatusData(Name alias, Table<EhrStatusDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private EhrStatusData(Name alias, Table<EhrStatusDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.ehr_status_data</code> table reference
     */
    public EhrStatusData(String alias) {
        this(DSL.name(alias), EHR_STATUS_DATA);
    }

    /**
     * Create an aliased <code>ehr.ehr_status_data</code> table reference
     */
    public EhrStatusData(Name alias) {
        this(alias, EHR_STATUS_DATA);
    }

    /**
     * Create a <code>ehr.ehr_status_data</code> table reference
     */
    public EhrStatusData() {
        this(DSL.name("ehr_status_data"), null);
    }

    public <O extends Record> EhrStatusData(Table<O> child, ForeignKey<O, EhrStatusDataRecord> key) {
        super(child, key, EHR_STATUS_DATA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : org.ehrbase.migration.importer.v4.jooq.pg.Ehr.EHR;
    }

    @Override
    public UniqueKey<EhrStatusDataRecord> getPrimaryKey() {
        return Keys.EHR_STATUS_PKEY;
    }

    @Override
    public List<ForeignKey<EhrStatusDataRecord, ?>> getReferences() {
        return Arrays.asList(
                Keys.EHR_STATUS_DATA__EHR_STATUS_DATA_EHR_ID_FKEY, Keys.EHR_STATUS_DATA__EHR_STATUS_EHR_ID_FKEY);
    }

    private transient EhrStatusVersion _ehrStatusVersion;
    private transient org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr _ehr;

    /**
     * Get the implicit join path to the <code>ehr.ehr_status_version</code>
     * table.
     */
    public EhrStatusVersion ehrStatusVersion() {
        if (_ehrStatusVersion == null)
            _ehrStatusVersion = new EhrStatusVersion(this, Keys.EHR_STATUS_DATA__EHR_STATUS_DATA_EHR_ID_FKEY);

        return _ehrStatusVersion;
    }

    /**
     * Get the implicit join path to the <code>ehr.ehr</code> table.
     */
    public org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr ehr() {
        if (_ehr == null)
            _ehr = new org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr(
                    this, Keys.EHR_STATUS_DATA__EHR_STATUS_EHR_ID_FKEY);

        return _ehr;
    }

    @Override
    public EhrStatusData as(String alias) {
        return new EhrStatusData(DSL.name(alias), this);
    }

    @Override
    public EhrStatusData as(Name alias) {
        return new EhrStatusData(alias, this);
    }

    @Override
    public EhrStatusData as(Table<?> alias) {
        return new EhrStatusData(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusData rename(String name) {
        return new EhrStatusData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusData rename(Name name) {
        return new EhrStatusData(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusData rename(Table<?> name) {
        return new EhrStatusData(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<
                    UUID,
                    Integer,
                    UUID,
                    Integer,
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    Integer,
                    JSONB>
            fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(
            Function14<
                            ? super UUID,
                            ? super Integer,
                            ? super UUID,
                            ? super Integer,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super Integer,
                            ? super JSONB,
                            ? extends U>
                    from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
            Class<U> toType,
            Function14<
                            ? super UUID,
                            ? super Integer,
                            ? super UUID,
                            ? super Integer,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super Integer,
                            ? super JSONB,
                            ? extends U>
                    from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
