/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import org.ehrbase.migration.importer.v4.jooq.pg.Keys;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.records.EhrStatusDataHistoryRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function15;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EhrStatusDataHistory extends TableImpl<EhrStatusDataHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.ehr_status_data_history</code>
     */
    public static final EhrStatusDataHistory EHR_STATUS_DATA_HISTORY = new EhrStatusDataHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EhrStatusDataHistoryRecord> getRecordType() {
        return EhrStatusDataHistoryRecord.class;
    }

    /**
     * The column <code>ehr.ehr_status_data_history.vo_id</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, UUID> VO_ID =
            createField(DSL.name("vo_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.num</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, Integer> NUM =
            createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.ehr_id</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, UUID> EHR_ID =
            createField(DSL.name("ehr_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.citem_num</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, Integer> CITEM_NUM =
            createField(DSL.name("citem_num"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.rm_entity</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> RM_ENTITY =
            createField(DSL.name("rm_entity"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_concept</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_CONCEPT =
            createField(DSL.name("entity_concept"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_name</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_NAME =
            createField(DSL.name("entity_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_attribute</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_ATTRIBUTE =
            createField(DSL.name("entity_attribute"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_path</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_PATH =
            createField(DSL.name("entity_path"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_path_cap</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_PATH_CAP =
            createField(DSL.name("entity_path_cap"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_idx</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_IDX =
            createField(DSL.name("entity_idx"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_idx_cap</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, String> ENTITY_IDX_CAP =
            createField(DSL.name("entity_idx_cap"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.entity_idx_len</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, Integer> ENTITY_IDX_LEN =
            createField(DSL.name("entity_idx_len"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.data</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, JSONB> DATA =
            createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_data_history.sys_version</code>.
     */
    public final TableField<EhrStatusDataHistoryRecord, Integer> SYS_VERSION =
            createField(DSL.name("sys_version"), SQLDataType.INTEGER.nullable(false), this, "");

    private EhrStatusDataHistory(Name alias, Table<EhrStatusDataHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private EhrStatusDataHistory(Name alias, Table<EhrStatusDataHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.ehr_status_data_history</code> table
     * reference
     */
    public EhrStatusDataHistory(String alias) {
        this(DSL.name(alias), EHR_STATUS_DATA_HISTORY);
    }

    /**
     * Create an aliased <code>ehr.ehr_status_data_history</code> table
     * reference
     */
    public EhrStatusDataHistory(Name alias) {
        this(alias, EHR_STATUS_DATA_HISTORY);
    }

    /**
     * Create a <code>ehr.ehr_status_data_history</code> table reference
     */
    public EhrStatusDataHistory() {
        this(DSL.name("ehr_status_data_history"), null);
    }

    public <O extends Record> EhrStatusDataHistory(Table<O> child, ForeignKey<O, EhrStatusDataHistoryRecord> key) {
        super(child, key, EHR_STATUS_DATA_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : org.ehrbase.migration.importer.v4.jooq.pg.Ehr.EHR;
    }

    @Override
    public UniqueKey<EhrStatusDataHistoryRecord> getPrimaryKey() {
        return Keys.EHR_STATUS_HISTORY_PKEY;
    }

    @Override
    public List<ForeignKey<EhrStatusDataHistoryRecord, ?>> getReferences() {
        return Arrays.asList(
                Keys.EHR_STATUS_DATA_HISTORY__EHR_STATUS_DATA_HISTORY_EHR_ID_SYS_VERSION_FKEY,
                Keys.EHR_STATUS_DATA_HISTORY__EHR_STATUS_HISTORY_EHR_ID_FKEY);
    }

    private transient EhrStatusVersionHistory _ehrStatusVersionHistory;
    private transient org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr _ehr;

    /**
     * Get the implicit join path to the
     * <code>ehr.ehr_status_version_history</code> table.
     */
    public EhrStatusVersionHistory ehrStatusVersionHistory() {
        if (_ehrStatusVersionHistory == null)
            _ehrStatusVersionHistory = new EhrStatusVersionHistory(
                    this, Keys.EHR_STATUS_DATA_HISTORY__EHR_STATUS_DATA_HISTORY_EHR_ID_SYS_VERSION_FKEY);

        return _ehrStatusVersionHistory;
    }

    /**
     * Get the implicit join path to the <code>ehr.ehr</code> table.
     */
    public org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr ehr() {
        if (_ehr == null)
            _ehr = new org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr(
                    this, Keys.EHR_STATUS_DATA_HISTORY__EHR_STATUS_HISTORY_EHR_ID_FKEY);

        return _ehr;
    }

    @Override
    public EhrStatusDataHistory as(String alias) {
        return new EhrStatusDataHistory(DSL.name(alias), this);
    }

    @Override
    public EhrStatusDataHistory as(Name alias) {
        return new EhrStatusDataHistory(alias, this);
    }

    @Override
    public EhrStatusDataHistory as(Table<?> alias) {
        return new EhrStatusDataHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusDataHistory rename(String name) {
        return new EhrStatusDataHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusDataHistory rename(Name name) {
        return new EhrStatusDataHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusDataHistory rename(Table<?> name) {
        return new EhrStatusDataHistory(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<
                    UUID,
                    Integer,
                    UUID,
                    Integer,
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    Integer,
                    JSONB,
                    Integer>
            fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(
            Function15<
                            ? super UUID,
                            ? super Integer,
                            ? super UUID,
                            ? super Integer,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super Integer,
                            ? super JSONB,
                            ? super Integer,
                            ? extends U>
                    from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
            Class<U> toType,
            Function15<
                            ? super UUID,
                            ? super Integer,
                            ? super UUID,
                            ? super Integer,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super String,
                            ? super Integer,
                            ? super JSONB,
                            ? super Integer,
                            ? extends U>
                    from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
