/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;
import org.ehrbase.migration.importer.v4.jooq.pg.Indexes;
import org.ehrbase.migration.importer.v4.jooq.pg.Keys;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.records.EhrStatusVersionRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EhrStatusVersion extends TableImpl<EhrStatusVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.ehr_status_version</code>
     */
    public static final EhrStatusVersion EHR_STATUS_VERSION = new EhrStatusVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EhrStatusVersionRecord> getRecordType() {
        return EhrStatusVersionRecord.class;
    }

    /**
     * The column <code>ehr.ehr_status_version.vo_id</code>.
     */
    public final TableField<EhrStatusVersionRecord, UUID> VO_ID =
            createField(DSL.name("vo_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_version.ehr_id</code>.
     */
    public final TableField<EhrStatusVersionRecord, UUID> EHR_ID =
            createField(DSL.name("ehr_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_version.contribution_id</code>.
     */
    public final TableField<EhrStatusVersionRecord, UUID> CONTRIBUTION_ID =
            createField(DSL.name("contribution_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_version.audit_id</code>.
     */
    public final TableField<EhrStatusVersionRecord, UUID> AUDIT_ID =
            createField(DSL.name("audit_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_version.sys_version</code>.
     */
    public final TableField<EhrStatusVersionRecord, Integer> SYS_VERSION =
            createField(DSL.name("sys_version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ehr.ehr_status_version.sys_period_lower</code>.
     */
    public final TableField<EhrStatusVersionRecord, OffsetDateTime> SYS_PERIOD_LOWER = createField(
            DSL.name("sys_period_lower"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private EhrStatusVersion(Name alias, Table<EhrStatusVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private EhrStatusVersion(Name alias, Table<EhrStatusVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.ehr_status_version</code> table reference
     */
    public EhrStatusVersion(String alias) {
        this(DSL.name(alias), EHR_STATUS_VERSION);
    }

    /**
     * Create an aliased <code>ehr.ehr_status_version</code> table reference
     */
    public EhrStatusVersion(Name alias) {
        this(alias, EHR_STATUS_VERSION);
    }

    /**
     * Create a <code>ehr.ehr_status_version</code> table reference
     */
    public EhrStatusVersion() {
        this(DSL.name("ehr_status_version"), null);
    }

    public <O extends Record> EhrStatusVersion(Table<O> child, ForeignKey<O, EhrStatusVersionRecord> key) {
        super(child, key, EHR_STATUS_VERSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : org.ehrbase.migration.importer.v4.jooq.pg.Ehr.EHR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EHR_STATUS_VERSION_SYS_PERIOD_LOWER_IDX);
    }

    @Override
    public UniqueKey<EhrStatusVersionRecord> getPrimaryKey() {
        return Keys.EHR_STATUS_VERSION_PKEY;
    }

    @Override
    public List<ForeignKey<EhrStatusVersionRecord, ?>> getReferences() {
        return Arrays.asList(
                Keys.EHR_STATUS_VERSION__EHR_STATUS_VERSION_EHR_ID_FKEY,
                Keys.EHR_STATUS_VERSION__EHR_STATUS_VERSION_CONTRIBUTION_ID_FKEY,
                Keys.EHR_STATUS_VERSION__EHR_STATUS_VERSION_AUDIT_ID_FKEY);
    }

    private transient org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr _ehr;
    private transient Contribution _contribution;
    private transient AuditDetails _auditDetails;

    /**
     * Get the implicit join path to the <code>ehr.ehr</code> table.
     */
    public org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr ehr() {
        if (_ehr == null)
            _ehr = new org.ehrbase.migration.importer.v4.jooq.pg.tables.Ehr(
                    this, Keys.EHR_STATUS_VERSION__EHR_STATUS_VERSION_EHR_ID_FKEY);

        return _ehr;
    }

    /**
     * Get the implicit join path to the <code>ehr.contribution</code> table.
     */
    public Contribution contribution() {
        if (_contribution == null)
            _contribution = new Contribution(this, Keys.EHR_STATUS_VERSION__EHR_STATUS_VERSION_CONTRIBUTION_ID_FKEY);

        return _contribution;
    }

    /**
     * Get the implicit join path to the <code>ehr.audit_details</code> table.
     */
    public AuditDetails auditDetails() {
        if (_auditDetails == null)
            _auditDetails = new AuditDetails(this, Keys.EHR_STATUS_VERSION__EHR_STATUS_VERSION_AUDIT_ID_FKEY);

        return _auditDetails;
    }

    @Override
    public EhrStatusVersion as(String alias) {
        return new EhrStatusVersion(DSL.name(alias), this);
    }

    @Override
    public EhrStatusVersion as(Name alias) {
        return new EhrStatusVersion(alias, this);
    }

    @Override
    public EhrStatusVersion as(Table<?> alias) {
        return new EhrStatusVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusVersion rename(String name) {
        return new EhrStatusVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusVersion rename(Name name) {
        return new EhrStatusVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EhrStatusVersion rename(Table<?> name) {
        return new EhrStatusVersion(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, UUID, Integer, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(
            Function6<
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super Integer,
                            ? super OffsetDateTime,
                            ? extends U>
                    from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
            Class<U> toType,
            Function6<
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super UUID,
                            ? super Integer,
                            ? super OffsetDateTime,
                            ? extends U>
                    from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
