/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables.records;

import java.util.UUID;
import org.ehrbase.migration.importer.v4.jooq.pg.enums.ContributionDataType;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.Contribution;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ContributionRecord extends UpdatableRecordImpl<ContributionRecord>
        implements Record5<UUID, UUID, ContributionDataType, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.contribution.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.contribution.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>ehr.contribution.ehr_id</code>.
     */
    public void setEhrId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>ehr.contribution.ehr_id</code>.
     */
    public UUID getEhrId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>ehr.contribution.contribution_type</code>.
     */
    public void setContributionType(ContributionDataType value) {
        set(2, value);
    }

    /**
     * Getter for <code>ehr.contribution.contribution_type</code>.
     */
    public ContributionDataType getContributionType() {
        return (ContributionDataType) get(2);
    }

    /**
     * Setter for <code>ehr.contribution.signature</code>.
     */
    public void setSignature(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ehr.contribution.signature</code>.
     */
    public String getSignature() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ehr.contribution.has_audit</code>.
     */
    public void setHasAudit(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>ehr.contribution.has_audit</code>.
     */
    public UUID getHasAudit() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, ContributionDataType, String, UUID> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, ContributionDataType, String, UUID> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Contribution.CONTRIBUTION.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Contribution.CONTRIBUTION.EHR_ID;
    }

    @Override
    public Field<ContributionDataType> field3() {
        return Contribution.CONTRIBUTION.CONTRIBUTION_TYPE;
    }

    @Override
    public Field<String> field4() {
        return Contribution.CONTRIBUTION.SIGNATURE;
    }

    @Override
    public Field<UUID> field5() {
        return Contribution.CONTRIBUTION.HAS_AUDIT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getEhrId();
    }

    @Override
    public ContributionDataType component3() {
        return getContributionType();
    }

    @Override
    public String component4() {
        return getSignature();
    }

    @Override
    public UUID component5() {
        return getHasAudit();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getEhrId();
    }

    @Override
    public ContributionDataType value3() {
        return getContributionType();
    }

    @Override
    public String value4() {
        return getSignature();
    }

    @Override
    public UUID value5() {
        return getHasAudit();
    }

    @Override
    public ContributionRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ContributionRecord value2(UUID value) {
        setEhrId(value);
        return this;
    }

    @Override
    public ContributionRecord value3(ContributionDataType value) {
        setContributionType(value);
        return this;
    }

    @Override
    public ContributionRecord value4(String value) {
        setSignature(value);
        return this;
    }

    @Override
    public ContributionRecord value5(UUID value) {
        setHasAudit(value);
        return this;
    }

    @Override
    public ContributionRecord values(
            UUID value1, UUID value2, ContributionDataType value3, String value4, UUID value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContributionRecord
     */
    public ContributionRecord() {
        super(Contribution.CONTRIBUTION);
    }

    /**
     * Create a detached, initialised ContributionRecord
     */
    public ContributionRecord(
            UUID id, UUID ehrId, ContributionDataType contributionType, String signature, UUID hasAudit) {
        super(Contribution.CONTRIBUTION);

        setId(id);
        setEhrId(ehrId);
        setContributionType(contributionType);
        setSignature(signature);
        setHasAudit(hasAudit);
        resetChangedOnNotNull();
    }
}
