/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables.records;

import java.time.OffsetDateTime;
import java.util.UUID;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.EhrFolderVersion;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EhrFolderVersionRecord extends UpdatableRecordImpl<EhrFolderVersionRecord>
        implements Record7<UUID, UUID, UUID, UUID, Integer, OffsetDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.ehr_folder_version.vo_id</code>.
     */
    public void setVoId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.vo_id</code>.
     */
    public UUID getVoId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>ehr.ehr_folder_version.ehr_id</code>.
     */
    public void setEhrId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.ehr_id</code>.
     */
    public UUID getEhrId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>ehr.ehr_folder_version.contribution_id</code>.
     */
    public void setContributionId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.contribution_id</code>.
     */
    public UUID getContributionId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>ehr.ehr_folder_version.audit_id</code>.
     */
    public void setAuditId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.audit_id</code>.
     */
    public UUID getAuditId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>ehr.ehr_folder_version.sys_version</code>.
     */
    public void setSysVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.sys_version</code>.
     */
    public Integer getSysVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ehr.ehr_folder_version.sys_period_lower</code>.
     */
    public void setSysPeriodLower(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.sys_period_lower</code>.
     */
    public OffsetDateTime getSysPeriodLower() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>ehr.ehr_folder_version.ehr_folders_idx</code>.
     */
    public void setEhrFoldersIdx(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ehr.ehr_folder_version.ehr_folders_idx</code>.
     */
    public Integer getEhrFoldersIdx() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, UUID, UUID, Integer, OffsetDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, UUID, UUID, Integer, OffsetDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.VO_ID;
    }

    @Override
    public Field<UUID> field2() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.EHR_ID;
    }

    @Override
    public Field<UUID> field3() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.CONTRIBUTION_ID;
    }

    @Override
    public Field<UUID> field4() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.AUDIT_ID;
    }

    @Override
    public Field<Integer> field5() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.SYS_VERSION;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.SYS_PERIOD_LOWER;
    }

    @Override
    public Field<Integer> field7() {
        return EhrFolderVersion.EHR_FOLDER_VERSION.EHR_FOLDERS_IDX;
    }

    @Override
    public UUID component1() {
        return getVoId();
    }

    @Override
    public UUID component2() {
        return getEhrId();
    }

    @Override
    public UUID component3() {
        return getContributionId();
    }

    @Override
    public UUID component4() {
        return getAuditId();
    }

    @Override
    public Integer component5() {
        return getSysVersion();
    }

    @Override
    public OffsetDateTime component6() {
        return getSysPeriodLower();
    }

    @Override
    public Integer component7() {
        return getEhrFoldersIdx();
    }

    @Override
    public UUID value1() {
        return getVoId();
    }

    @Override
    public UUID value2() {
        return getEhrId();
    }

    @Override
    public UUID value3() {
        return getContributionId();
    }

    @Override
    public UUID value4() {
        return getAuditId();
    }

    @Override
    public Integer value5() {
        return getSysVersion();
    }

    @Override
    public OffsetDateTime value6() {
        return getSysPeriodLower();
    }

    @Override
    public Integer value7() {
        return getEhrFoldersIdx();
    }

    @Override
    public EhrFolderVersionRecord value1(UUID value) {
        setVoId(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord value2(UUID value) {
        setEhrId(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord value3(UUID value) {
        setContributionId(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord value4(UUID value) {
        setAuditId(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord value5(Integer value) {
        setSysVersion(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord value6(OffsetDateTime value) {
        setSysPeriodLower(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord value7(Integer value) {
        setEhrFoldersIdx(value);
        return this;
    }

    @Override
    public EhrFolderVersionRecord values(
            UUID value1, UUID value2, UUID value3, UUID value4, Integer value5, OffsetDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EhrFolderVersionRecord
     */
    public EhrFolderVersionRecord() {
        super(EhrFolderVersion.EHR_FOLDER_VERSION);
    }

    /**
     * Create a detached, initialised EhrFolderVersionRecord
     */
    public EhrFolderVersionRecord(
            UUID voId,
            UUID ehrId,
            UUID contributionId,
            UUID auditId,
            Integer sysVersion,
            OffsetDateTime sysPeriodLower,
            Integer ehrFoldersIdx) {
        super(EhrFolderVersion.EHR_FOLDER_VERSION);

        setVoId(voId);
        setEhrId(ehrId);
        setContributionId(contributionId);
        setAuditId(auditId);
        setSysVersion(sysVersion);
        setSysPeriodLower(sysPeriodLower);
        setEhrFoldersIdx(ehrFoldersIdx);
        resetChangedOnNotNull();
    }
}
