/*
 * Copyright (c) 2024 vitasystems GmbH
 *
 * This file is part of project EHRbase Migration Tool
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.migration.importer.v4.jooq.pg.tables.records;

import java.time.OffsetDateTime;
import java.util.UUID;
import org.ehrbase.migration.importer.v4.jooq.pg.tables.EhrStatusVersionHistory;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EhrStatusVersionHistoryRecord extends UpdatableRecordImpl<EhrStatusVersionHistoryRecord>
        implements Record8<UUID, UUID, UUID, UUID, Integer, OffsetDateTime, OffsetDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.ehr_status_version_history.vo_id</code>.
     */
    public void setVoId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.vo_id</code>.
     */
    public UUID getVoId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.ehr_id</code>.
     */
    public void setEhrId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.ehr_id</code>.
     */
    public UUID getEhrId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.contribution_id</code>.
     */
    public void setContributionId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.contribution_id</code>.
     */
    public UUID getContributionId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.audit_id</code>.
     */
    public void setAuditId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.audit_id</code>.
     */
    public UUID getAuditId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.sys_version</code>.
     */
    public void setSysVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.sys_version</code>.
     */
    public Integer getSysVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.sys_period_lower</code>.
     */
    public void setSysPeriodLower(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.sys_period_lower</code>.
     */
    public OffsetDateTime getSysPeriodLower() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.sys_period_upper</code>.
     */
    public void setSysPeriodUpper(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.sys_period_upper</code>.
     */
    public OffsetDateTime getSysPeriodUpper() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>ehr.ehr_status_version_history.sys_deleted</code>.
     */
    public void setSysDeleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>ehr.ehr_status_version_history.sys_deleted</code>.
     */
    public Boolean getSysDeleted() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, UUID, UUID, Integer, OffsetDateTime, OffsetDateTime, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, UUID, UUID, UUID, Integer, OffsetDateTime, OffsetDateTime, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.VO_ID;
    }

    @Override
    public Field<UUID> field2() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.EHR_ID;
    }

    @Override
    public Field<UUID> field3() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.CONTRIBUTION_ID;
    }

    @Override
    public Field<UUID> field4() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.AUDIT_ID;
    }

    @Override
    public Field<Integer> field5() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.SYS_VERSION;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.SYS_PERIOD_LOWER;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.SYS_PERIOD_UPPER;
    }

    @Override
    public Field<Boolean> field8() {
        return EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY.SYS_DELETED;
    }

    @Override
    public UUID component1() {
        return getVoId();
    }

    @Override
    public UUID component2() {
        return getEhrId();
    }

    @Override
    public UUID component3() {
        return getContributionId();
    }

    @Override
    public UUID component4() {
        return getAuditId();
    }

    @Override
    public Integer component5() {
        return getSysVersion();
    }

    @Override
    public OffsetDateTime component6() {
        return getSysPeriodLower();
    }

    @Override
    public OffsetDateTime component7() {
        return getSysPeriodUpper();
    }

    @Override
    public Boolean component8() {
        return getSysDeleted();
    }

    @Override
    public UUID value1() {
        return getVoId();
    }

    @Override
    public UUID value2() {
        return getEhrId();
    }

    @Override
    public UUID value3() {
        return getContributionId();
    }

    @Override
    public UUID value4() {
        return getAuditId();
    }

    @Override
    public Integer value5() {
        return getSysVersion();
    }

    @Override
    public OffsetDateTime value6() {
        return getSysPeriodLower();
    }

    @Override
    public OffsetDateTime value7() {
        return getSysPeriodUpper();
    }

    @Override
    public Boolean value8() {
        return getSysDeleted();
    }

    @Override
    public EhrStatusVersionHistoryRecord value1(UUID value) {
        setVoId(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value2(UUID value) {
        setEhrId(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value3(UUID value) {
        setContributionId(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value4(UUID value) {
        setAuditId(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value5(Integer value) {
        setSysVersion(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value6(OffsetDateTime value) {
        setSysPeriodLower(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value7(OffsetDateTime value) {
        setSysPeriodUpper(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord value8(Boolean value) {
        setSysDeleted(value);
        return this;
    }

    @Override
    public EhrStatusVersionHistoryRecord values(
            UUID value1,
            UUID value2,
            UUID value3,
            UUID value4,
            Integer value5,
            OffsetDateTime value6,
            OffsetDateTime value7,
            Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EhrStatusVersionHistoryRecord
     */
    public EhrStatusVersionHistoryRecord() {
        super(EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY);
    }

    /**
     * Create a detached, initialised EhrStatusVersionHistoryRecord
     */
    public EhrStatusVersionHistoryRecord(
            UUID voId,
            UUID ehrId,
            UUID contributionId,
            UUID auditId,
            Integer sysVersion,
            OffsetDateTime sysPeriodLower,
            OffsetDateTime sysPeriodUpper,
            Boolean sysDeleted) {
        super(EhrStatusVersionHistory.EHR_STATUS_VERSION_HISTORY);

        setVoId(voId);
        setEhrId(ehrId);
        setContributionId(contributionId);
        setAuditId(auditId);
        setSysVersion(sysVersion);
        setSysPeriodLower(sysPeriodLower);
        setSysPeriodUpper(sysPeriodUpper);
        setSysDeleted(sysDeleted);
        resetChangedOnNotNull();
    }
}
