name: Build and push

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]

    steps:
      # Install the migration tool in the local repo
      - name: Checkout Migration Tool
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ehrbase/migration-tool
          ref: develop
          # This will be used by git in all further steps
          # We need a PERSONAL ACCESS TOKEN so pushes trigger other github actions
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Install Migration Tool
        run: mvn install

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitLab
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Spotless
        run: mvn spotless:check
      - name: install migration tool main
        run: mvn install -Dmaven.test.skip=true


      - name: Build with Maven
        run: mvn clean verify spring-boot:build-image

      - name: Build and push
        if: ${{ github.ref == 'ref/head/develop' }} || ${{ github.ref == 'ref/head/master' }} || ${{ github.ref == 'ref/head/main' }}
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)       
          docker push ehrbase/migration-tool:${VERSION}
  
